/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package com.jpl.lego.bo;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author José Pereda Llamas
 * Created on 10-nov-2012 - 19:32:59
 */
@javax.ws.rs.ApplicationPath("NXT")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        return getRestResourceClasses();
    }

    /**
     * Do not modify this method. It is automatically generated by NetBeans REST support.
     */
    private Set<Class<?>> getRestResourceClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        resources.add(com.jpl.lego.bo.rest.MotorResource.class);
        resources.add(com.jpl.lego.bo.rest.DeviceResource.class);
        resources.add(com.jpl.lego.bo.rest.VolumeResource.class);
        resources.add(com.jpl.lego.bo.rest.SearchResource.class);
        return resources;
    }

}
